// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ParseConfig() {
  return window['go']['main']['App']['ParseConfig']();
}

export function StartVPN(arg1) {
  return window['go']['main']['App']['StartVPN'](arg1);
}

export function WriteConfig(arg1) {
  return window['go']['main']['App']['WriteConfig'](arg1);
}
