// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ParseConfig():Promise<main.AppConfig>;

export function StartVPN(arg1:main.Subscription):Promise<void>;

export function WriteConfig(arg1:main.AppConfig):Promise<boolean>;
